In [2]:
import array
L=list(range(10))
A=array.array('l',L)
A

array('l', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(A)

array.array

In [4]:
import numpy as np

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([1,2,3],dtype='float32')

array([1., 2., 3.], dtype=float32)

In [8]:
np.array([range(i,i+3) for i in [2,4,6] ] )

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
print([range(i,i+3) for i in [2,4,6] ] )

[range(2, 5), range(4, 7), range(6, 9)]


## Creating array from scratch

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.array(range(0,20,2))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
print("create array 1-5 : range ")
np.linspace (0,1,5)

create array 1-5 : range 


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.random.random((3,3))

array([[0.13408483, 0.68285805, 0.90665442],
       [0.16682813, 0.32445394, 0.41378146],
       [0.75924787, 0.80794276, 0.59032811]])

In [29]:
np.random.random((3,3))

array([[0.63080299, 0.80964956, 0.41394623],
       [0.60816199, 0.91787125, 0.86786555],
       [0.57924723, 0.11127993, 0.28831471]])

In [31]:
print("Create 3X3 array normally distributed 0:mean 1:std ")
np.random.normal(0,1,(3,3))

Create 3X3 array normally distributed 0:mean 1:std 


array([[ 0.80277137, -0.44206439,  0.44806599],
       [ 0.55270698,  0.8253241 ,  0.67595477],
       [-0.31426916,  0.43796724,  0.32827819]])

In [37]:
np.random.randint(0,10)

7

In [38]:
np.random.randint(0,10,(3,3))

array([[2, 9, 1],
       [2, 3, 9],
       [6, 0, 6]])

In [40]:
print("Identity matrix")
np.eye(3)


Identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])