# Structured Data : Numpy's Structured Arrays

In [1]:
import numpy as np

In [2]:
name=['alice','bob','cathy','doug']
age=[25,45,37,19]
weight=[55,85.5,68,61.5]


In [3]:
x=np.zeros(4,dtype=int)
x

array([0, 0, 0, 0])

In [4]:
data=np.zeros(4,dtype={'names': ('name','age','weight'),
                      'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [5]:
data['name']=name
data['age']=age
data['weight']=weight
print(data)

[('alice', 25, 55. ) ('bob', 45, 85.5) ('cathy', 37, 68. )
 ('doug', 19, 61.5)]


In [6]:
data['name']

array(['alice', 'bob', 'cathy', 'doug'], dtype='<U10')

In [7]:
data['age']<30

array([ True, False, False,  True])

In [9]:
data[data['age']<30]['name']

array(['alice', 'doug'], dtype='<U10')

## Creating structed arrays

In [12]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

## more advance compound types

In [15]:
tp=np.dtype([('id','i8'),('mat','f8',(3,3))])
x=np.zeros(1,dtype=tp)
x

array([(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
      dtype=[('id', '<i8'), ('mat', '<f8', (3, 3))])

In [16]:
print(x[0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])


In [20]:
print(x['mat'][0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Record Arrays : Structured array with a twist

NumPy also provides the np.recarray class, which is almost identical to the structured arrays just described, but with one additional feature: fields can be accessed as attributes rather than as dictionary keys

In [22]:
data['age']

array([25, 45, 37, 19])

In [23]:
data_rec=data.view(np.recarray)
data_rec

rec.array([('alice', 25, 55. ), ('bob', 45, 85.5), ('cathy', 37, 68. ),
           ('doug', 19, 61.5)],
          dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [24]:
data_rec.age

array([25, 45, 37, 19])

In [25]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

249 ns ± 4.33 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
7.19 µs ± 507 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
13.3 µs ± 832 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
