In [1]:
import numpy as np

In [15]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

print(x1)
print("----------")
print(x2)
print("__________")
print(x3)

print("Always choose random value")

[4 7 2 6 1 3]
----------
[[3 5 2 7]
 [3 0 5 4]
 [0 3 6 0]]
__________
[[[1 5 3 4 5]
  [2 0 3 3 8]
  [2 5 6 0 5]
  [4 6 0 2 7]]

 [[8 1 6 4 6]
  [1 7 7 1 5]
  [0 4 2 4 5]
  [6 8 3 2 4]]

 [[5 4 6 5 1]
  [7 2 3 8 9]
  [1 8 3 8 2]
  [5 8 5 8 2]]]
Always choose random value


In [20]:
np.random.seed(0)

x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

print(x1)
print("----------")
print(x2)
print("__________")
print(x3)

print("Always choose fixed  value")

[5 0 3 3 7 9]
----------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
__________
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
Always choose fixed  value


In [25]:
x3.ndim,x3.shape,x3.size,x2.dtype,x3.itemsize,x3.nbytes

(3, (3, 4, 5), 60, dtype('int32'), 4, 240)

## Array indexing : Accessing Single elements

In [26]:
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[-1]

9

In [28]:
x2[0,0]

3

## Array slicing :Accessing subarray

In [31]:
x=np.arange(10)

In [32]:
x[3:7]

array([3, 4, 5, 6])

In [35]:
x[::3]

array([0, 3, 6, 9])

In [37]:
x[1::2]

array([1, 3, 5, 7, 9])

In [38]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
x[5::-2]

array([5, 3, 1])

In [41]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
print("2 row ,3 col")
x2[:2,:3]

2 row ,3 col


array([[3, 5, 2],
       [7, 6, 8]])

In [46]:
print("all row ,every other col")
x2[:3,::2]

all row ,every other col


array([[3, 2],
       [7, 8],
       [1, 7]])

In [48]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [49]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [51]:
print("first col of x2")
x2[:,0]

first col of x2


array([3, 7, 1])

In [53]:
print("first row of x2")
x2[0,:]

first row of x2


array([3, 5, 2, 4])

In [55]:
x2[1,:]

array([7, 6, 8, 8])

## Subarrays as no copy views

In [56]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [57]:
x2_sub=x2[:2,:2]
x2_sub

array([[3, 5],
       [7, 6]])