In [1]:
import numpy as np

In [2]:
grid=np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
x=np.array([1,2,3])
x.reshape(1,3)

array([[1, 2, 3]])

In [7]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [9]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [13]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])