In [2]:
import numpy as np

x=np.array([1,2,3])
y=np.array([4,5,6])


In [4]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
z=np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## concate in 2 D 

In [8]:
grid=np.array([[1,2,3],
              [4,5,6]])

In [13]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [14]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Horizontal and vertical stack

In [16]:
x=np.array([1,2,3])
grid=np.array([[4,5,6],
               [7,8,9]])

In [18]:
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
y=np.array([[10],[11]])

In [21]:
np.hstack([grid,y])

array([[ 4,  5,  6, 10],
       [ 7,  8,  9, 11]])

# splitting of arrays

In [30]:
x=[1,2,3,4,5,6,7,8,9]
x1,x2,x3=np.split(x,([2,5])) # (2,5) are index position
print(x1,x2,x3)

[1 2] [3 4 5] [6 7 8 9]


In [31]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
upper,lower=np.vsplit(grid,[2]) #  [2] index position

In [37]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [38]:
upper,lower=np.hsplit(grid,[2]) #  [2] index position

In [39]:
print(upper)
print(lower)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
