In [2]:
import numpy as np

In [2]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [3]:
x+5

array([5, 6, 7, 8, 9])

In [4]:
x**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [5]:
np.add(x,2)

array([2, 3, 4, 5, 6])

## Absolute value

In [7]:
x=np.array(range(-3,3))
x

array([-3, -2, -1,  0,  1,  2])

In [9]:
np.abs(x)

array([3, 2, 1, 0, 1, 2])

In [14]:
x=np.array([3+4j,6+8j])
np.abs(x)

array([ 5., 10.])

In [15]:
x

array([3.+4.j, 6.+8.j])

# Trigonometric function

In [18]:
theta=np.linspace(0,np.pi ,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [19]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [20]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [22]:
np.arctan(theta)

array([0.        , 1.00388482, 1.26262726])

# Exponents and logarithms

In [24]:
x=[1,2,3,4]

In [26]:
print('e^x : ',np.exp(x))
print('x^2 : ',np.exp2(x))
print('x^3 : ',np.power(3,x))

e^x :  [ 2.71828183  7.3890561  20.08553692 54.59815003]
x^2 :  [ 2.  4.  8. 16.]
x^3 :  [ 3  9 27 81]


In [27]:
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [30]:
print('exp(x) -1 :',np.expm1(x))
print('log(1+x)  :',np.log1p(x))

exp(x) -1 : [ 1.71828183  6.3890561  19.08553692 53.59815003]
log(1+x)  : [0.69314718 1.09861229 1.38629436 1.60943791]


# Specialized ufuncs : Scipy Special

In [32]:
from scipy import special

In [33]:
# Gamma functions (genelalized factorials ) and relaxed functions

In [34]:
x=[1,2,3]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x,2))

[1. 1. 2.]
[0.         0.         0.69314718]
[0.5        0.16666667 0.08333333]


In [35]:
#Error function (integral of gaussian)
#its complement and its inverse

In [36]:
x=np.array([0,0.3,0.7,1.0])
print(special.erf(x))
print(special.erfc(x))
print(special.erfinv(x))

[0.         0.32862676 0.67780119 0.84270079]
[1.         0.67137324 0.32219881 0.15729921]
[0.         0.27246271 0.73286908        inf]


# Aggregates

In [3]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [41]:
np.add.reduce(x)

15

In [43]:
np.multiply.reduce(x)

120

In [44]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [4]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [5]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])