In [1]:
import numpy as np

In [3]:
L=np.random.random(100)
L

array([2.09823973e-01, 9.34937183e-02, 4.27183414e-01, 6.95708599e-01,
       1.20261899e-01, 8.23095102e-03, 8.82871573e-01, 8.29479296e-01,
       2.34835438e-01, 2.90484180e-01, 6.87933515e-01, 6.24108510e-02,
       5.76751138e-01, 3.91683059e-02, 1.54562626e-02, 7.57388166e-01,
       5.33280624e-01, 6.94158883e-01, 9.92330101e-01, 4.56909516e-01,
       1.66294192e-01, 9.49496229e-01, 2.87750991e-01, 1.52169573e-01,
       1.60404064e-01, 6.19662645e-01, 1.18359885e-01, 9.53091212e-01,
       3.75645726e-01, 2.54407031e-01, 8.61265342e-01, 5.53358478e-01,
       5.88540879e-01, 5.29179672e-01, 3.33043865e-02, 5.78404943e-01,
       1.26847840e-01, 5.34940773e-01, 5.43556412e-01, 5.71690801e-01,
       4.18988390e-02, 1.78944623e-01, 7.84709462e-01, 7.60517293e-01,
       6.28662182e-01, 8.99170019e-01, 3.05777312e-01, 7.73343776e-01,
       6.99260851e-01, 4.28249466e-01, 4.11858635e-01, 1.96095638e-01,
       2.64947951e-01, 4.77037822e-02, 4.08484490e-01, 1.95356053e-01,
      

In [4]:
sum(L)

45.58432637144494

In [5]:
np.sum(L)

45.58432637144493

In [6]:
big_array=np.random.rand(100000)
sum(big_array)

49976.64777696323

In [7]:
%timeit sum(big_array)
%timeit np.sum(big_array)

26.5 ms ± 886 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
217 µs ± 3.68 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
np.min(big_array) ,max(big_array)

(1.678223765289033e-06, 0.9999959831250976)

In [9]:
%timeit max(big_array)
%timeit np.max(big_array)

20.4 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
208 µs ± 8.49 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Multidimentional aggregates

In [15]:
M=np.random.randint(1,10,(3,4))
M

array([[2, 8, 8, 4],
       [5, 1, 5, 3],
       [2, 7, 4, 2]])

In [16]:
M.sum()

51

In [21]:
M.min(axis=0) # min in col

array([2, 1, 4, 2])

In [20]:
M.min(axis=1) # min in row

array([2, 1, 2])

In [24]:
M.max(axis=0)

array([5, 8, 8, 4])