In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
x


array([1, 2, 3, 4, 5])

In [3]:
x<2

array([ True, False, False, False, False])

In [4]:
x !=3

array([ True,  True, False,  True,  True])

In [5]:
(2 *x )==(x **2)

array([False,  True, False, False, False])

As in the case of arithmetic operators,
the comparison operators are implemented as ufuncs in NumPy; 
for example, when you write x < 3, internally NumPy uses np.less(x, 3)

In [13]:
# RandomState(0) : fixed the value in here
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [14]:
np.less_equal(x,5)

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

## Counting entries

In [19]:
np.sum(x<5)

6

In [20]:
np.count_nonzero(x<6)

8

In [22]:
np.sum(x<6,axis=1) # 5,0,3,3 #3,5 # 2,4

array([4, 2, 2])

In [24]:
np.any(x>8) # any value less than 8

True

In [25]:
np.all(x==6) # all value are 6

False

In [27]:
np.all(x<8,axis=1)

array([ True, False,  True])

# Boolean array as masks

In [29]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [30]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [33]:
x[x<5] # only True values are shown ,masking with True 

array([0, 3, 3, 3, 2, 4])

## keyword and / or vs operator & / | 

In [34]:
bool (42),bool(0)

(True, False)

In [35]:
bool (42 and 0)

False

In [36]:
bin (42)

'0b101010'

In [37]:
bin (42 & 59)

'0b101010'

In [40]:
A=np.array([0,1,1],dtype=bool)
B=np.array([0,1,0],dtype=bool)
A|B

array([False,  True,  True])

In [42]:
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()